### PR TITLE
Update nl.po translation based on Fixato's comments

### PR DESCRIPTION
**Pull request by martijndeb**
Add quotation marks around 'Fout melden', change the wording 'probleem' to 'issue';
Fix singular characters left translation and add missing word to the same plural definition.

Thanks @Fixato

### CODE REVIEW

**Comment by aral** [comment]
@sexybiggetje Thanks for this.

One request: can we please remove the quotes so as not to change the formatting in a translation. I’d like to keep that consistent. I’m assuming this is the name of the button, so we should have it capitalised as in the original. If that doesn’t work in general for some reason, let’s open an issue for changing the formatting of the string in all the localisations.

**Comment by sexybiggetje** [comment]
It's a common thing in Dutch to place quotation marks when indicating something, that isn't always true for other languages.
@fixato proposed to capitalize Melden, as well, but that looks quite wrong to me, because we don't capitalize the second word.

I truly don't know the best scenario. I'll ping @fixato

**Comment by sexybiggetje** [comment]
@aral I've removed the quotation marks, and capitalized Fout Melden fully as per @fixato's answer on Mastodon.

**Comment by aral** [comment]
@sexybiggetje @FIXato – thank you both; now merged and will be in the first release :)

**Pull request merged**
